# Generated by Django 4.0.3 on 2022-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
