# Generated by Django 4.0.3 on 2022-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_category_id_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
